infra:
  log_dir: ../train/ # where all the experiments are
  exp_name: msdsr_exp # use the same name as the training experiment
  comment: eval_volgen # can use this to customize for each experiment
  seed: 1000
data:
  valid_augmentation:
    - which: center_crop_always_apply
      params:
        size: 48
  rand_aug_prob: 1
  direct_params:
    val:
      data_root: TODO # path to z-stacked SRH dataset
      studies: [zsrh_001.pt] # list of pt file names
loader:
  direct_params:
    val:
      batch_size: 64
      drop_last: False
      pin_memory: True
      num_workers: 8
      persistent_workers: True
model:
  which: LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 48
    channels: 4
    monitor: val/loss_simple_ema
    beta_schedule: cosine
    loss_type: l1
    unet_config:
      which: UNetModel
      params:
        image_size: 48
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions: [8,4,2]
        num_res_blocks: 2
        channel_mult: [1,2,3,4]
        num_head_channels: 32
    first_stage_config:
      which: IdentityFirstStage
      params: {}
    conditioning_key: msdsr
    cond_stage_config: __is_first_stage__
    cond_stage_trainable: False
    concat_mode: False
eval:
  ckpt_path: msdsr_cvmi24/models/d17986ac.ckpt # relative path to checkpoint
  scale_factor: 2
  transpose_pred: False
